// AUTO-GENERATED by design-inventor
// Locksmith Luz — Fortress & Light: deep forest green authority with gold confidence signals
// Logo-anchored: YES — all hues from logo_colors (#d6b328, #217443, #62c794)
// CLIENT FEEDBACK: Design approved. CRITICAL FIX: nav CTA button must use explicit bg-[#d6b328] text-[#0d1a12]
//                 — never transparent/inherit — button was invisible in previous header. Fixed in this spec.

export const designConfig = {

  colors: {
    primary:       '#d6b328',  // gold from logo — CTA buttons, active states, gold accents
    primaryLight:  '#e8cc5a',  // lighter gold — hover states, gradient endpoints
    primaryDark:   '#a8891c',  // deeper gold — pressed states, text-on-light uses
    secondary:     '#217443',  // forest green from logo — headings, icon strokes, left bars
    accent:        '#62c794',  // mint green from logo — checkmarks, badges, success states
    background:    '#f5f9f6',  // pale green-white — light section backgrounds
    surface:       '#ffffff',  // pure white — cards, form inputs
    surfaceDark:   '#0f1e17',  // deep forest near-black — hero, FAQ, StatsBar, CTA left panel
    textPrimary:   '#0d1a12',  // near-black with green undertone — all body text on light sections
    textSecondary: '#4a6155',  // muted forest green-grey — descriptions, captions, secondary labels
    textLight:     '#FFFFFF',  // all text on dark sections
    border:        '#d4e6db',  // light mint-green — card borders, input borders on light sections
  },

  fonts: {
    display:           'Oswald',
    body:              'Nunito Sans',
    googleFontsUrl:    'https://fonts.googleapis.com/css2?family=Oswald:wght@400;600;700&family=Nunito+Sans:ital,opsz,wght@0,6..12,400;0,6..12,500;0,6..12,600;0,6..12,700;1,6..12,400&display=swap',
    headingWeight:     'font-bold',
    headingTracking:   'tracking-tight',
    headingLineHeight: 'leading-none',
    labelsUppercase:   true,  // all section pre-labels and nav links use Oswald uppercase
  },

  hero: {
    // "Fortress Command Hero"
    pattern:          'fortress-command',
    backgroundType:   'dark-image',        // full-screen photo covered by radial gradient overlay at 0.88 opacity
    contentAlignment: 'center',            // centered horizontally, 45% vertical position
    ctaShape:         'rounded-none',      // sharp geometry throughout — echoes shield motif
    hasStats:         false,               // no inline hero stats — StatsBar section handles this
    hasInlineForm:    true,                // 3-field quick-quote form panel with glassmorphism below CTA buttons
    hasTrustBadge:    true,                // "🔒 Licensed & Insured · California" chip above headline
    hasDualCTA:       true,                // primary gold filled + outlined white phone button side-by-side
    kenBurnsZoom:     true,                // scale(1.0→1.08) 12s ease-in-out infinite alternate
  },

  services: {
    // "Split Editorial Rows"
    pattern:                 'split-editorial-rows',
    requiresClientComponent: false,
    cardImageAspect:         'landscape',   // 4:3 aspect ratio images in split rows
    sectionBg:               'bg-background', // alternates between bg-white and bg-background per row
    headerAlignment:         'text-left',
    hasChecklist:            true,           // mint checkmark bullet points in text column
    hasGradientLeftBar:      true,           // Green-Gold Gradient Left Bar on split-row h3 headings
    rowAlternation:          'image-left-odd-text-right', // even rows: image(col-span-3) + text(col-span-2)
  },

  colorMood: {
    dominantTone: 'vibrant',   // vivid green + gold — not dark-only, not light-only
  },

  style: {
    name: 'fortress-authority',  // institutional authority with warmth

    // ⚠️ CRITICAL NAV FIX: phone CTA button in nav MUST be bg-[#d6b328] text-[#0d1a12] at ALL times
    // Do not use variant/conditional classes that could accidentally make it transparent over the hero
    headerType:   'transparent-sticky',  // transparent over hero → solid white on scroll past 80px
    hasMegaMenu:  false,
    hasTopBar:    false,
    mobileStyle:  'drawer-right',         // slide-in drawer from right, bg-[#0f1e17], Oswald 700 28px links

    // Richness mandate — 5 flags active (minimum 4 required)
    hasScrollProgress:    false,
    hasParallax:          true,   // services section images at 0.85× scroll speed
    hasFloatingBlobs:     true,   // StatsBar + CTA left panel — green/gold blobs at 6-8% opacity
    hasTiltCards:         false,
    hasMagneticButtons:   true,   // CTA form submit + hero form submit — 80px radius, 10px max
    hasSplitText:         true,   // hero headline word-by-word spring entry on load
    hasPinnedSteps:       true,   // ProcessSteps section pins ~300vh, steps activate on scroll
    hasCursorFollower:    false,
    counterStyle:         'ease-out',  // StatsBar: 1800ms cubic-bezier(0,0,0.2,1) — no overshoot

    hasImageMarquee:      true,   // dual-row trust marquee strip between hero and WhyUs
    hasProjectGallery:    false,
    hasSlideshowHero:     false,
    hasBeforeAfter:       false,  // locksmith — no clear visual transformation to show (correct per spec)
    hasPolaroidGallery:   false,
    hasHoverReveal:       false,
    hasHorizontalTheater: false,
    textDensity:          'standard',  // balanced — enough copy to communicate authority
  },

  sectionOrder: [
    'Hero',
    'WhyUs',        // 4-column icon feature grid — preceded by marquee trust strip
    'Services',     // split editorial alternating rows
    'StatsBar',     // authority numbers — 4 stats dark strip
    'ProcessSteps', // pinned scroll reveal — 4 steps
    'Testimonials', // review card grid — 3 columns
    'FAQ',          // tab category switcher — 4 tabs
    'Areas',        // badge chip grid — service area chips
    'CTA',          // split authority panel — dark left + gold right
  ],

  sections: {
    stats: {
      bg:          'bg-[#0f1e17]',
      textColor:   'text-white',
      numberColor: 'text-[#d6b328]',
      hasBlobs:    true,
    },
    testimonials: {
      style: 'card-grid',   // 3-column static grid, no carousel
      bg:    'bg-[#f5f9f6]',
    },
    faq: {
      style: 'tab-categories',  // 4 tabs: Home Lockouts, Emergency, Automotive, Commercial
      bg:    'bg-[#0f1e17]',
    },
    cta: {
      bg:               'split',  // left bg-[#0f1e17] / right bg-[#d6b328]
      hasBackgroundImage: false,
      hasFloatingBlobs:   true,   // left panel only
    },
    processSteps: {
      style: 'pinned-scroll',
      bg:    'bg-[#f5f9f6]',
    },
    areas: {
      style: 'badge-chip-grid',
      bg:    'bg-[#f5f9f6]',
    },
    whyUs: {
      style: 'icon-feature-grid',
      bg:    'bg-[#f5f9f6]',
    },
  },

  // Effects active on this site (for builder reference)
  effects: {
    kenBurnsHero:        true,   // hero bg photo scale(1.0→1.08) 12s infinite alternate
    marqueeStrip:        true,   // dual-row trust marquee before WhyUs, direction-opposite rows
    shimmerButton:       true,   // diagonal white glint sweeps all primary gold CTAs on hover
    gradientTextHero:    true,   // hero headline line 2 key word uses bg-clip:text gold gradient
    floatingBlobs:       true,   // StatsBar + CTA left panel
    parallaxServices:    true,   // service images 0.85× scroll speed
    counterEaseOut:      true,   // StatsBar number counters 1800ms cubic-bezier(0,0,0.2,1)
    splitTextSpring:     true,   // hero headline word cascade on page load
    springChipPop:       true,   // Areas section chips spring-pop staggered 40ms
    borderSlideHover:    true,   // testimonial card left border shifts green→gold on hover
  },

} as const;

export type DesignConfig = typeof designConfig;
